version: "3"

services:
  next-app:
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
    #   args:
    #     ENV_VARIABLE: ${ENV_VARIABLE}
    #     NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    # restart: always
    # env_file:
      # - .env
    ports:
      - 3000:3000


  
